---
- name: Testing andrewrothstein.bitcoin_core
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'bitcoin-cli --version'
      ansible.builtin.command: bitcoin-cli --version
      changed_when: false
      register: bitcoin_core_test_output
    - name: Output from 'bitcoin-cli --version'
      ansible.builtin.debug:
        msg: '{{ bitcoin_core_test_output.stdout }}'
