---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/bitcoin-cli --version
      register: bitcoin_core_test_output
    - name: bitcoin-cli --version
      debug:
        msg: '{{ bitcoin_core_test_output.stdout }}'
